image: registry.fvdh.dev/gradle:6.7-jdk11

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

authorization_build:
  stage: build
  script:
    gradle --build-cache :services:authorization:assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build/
      - .gradle/

authorization_checkStyle:
  stage: staticAnalysis
  script:
    gradle :services:authorization:checkstyleMain :services:authorization:checkstyleTest

authorization_PMD:
  stage: staticAnalysis
  script:
    gradle :services:authorization:pmdMain :services:authorization:pmdTest

authorization_test:
  stage: test
  script:
    gradle :services:authorization:test

