image: registry.fvdh.dev/gradle:6.7-jdk11

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

authentication_build:
  stage: build
  script:
    gradle --build-cache :services:authentication:assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build/
      - .gradle/

authentication_checkStyle:
  stage: staticAnalysis
  script:
    gradle :services:authentication:checkstyleMain :services:authentication:checkstyleTest

authentication_PMD:
  stage: staticAnalysis
  script:
    gradle :services:authentication:pmdMain :services:authentication:pmdTest

authentication_test:
  stage: test
  script:
    gradle :services:authentication:test

