image: registry.fvdh.dev/gradle:6.7-jdk11

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

course-service_build:
  stage: build
  script:
    gradle --build-cache :services:course-service:assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build/
      - .gradle/

course-service_checkStyle:
  stage: staticAnalysis
  script:
    gradle :services:course-service:checkstyleMain :services:course-service:checkstyleTest


course-service_PMD:
  stage: staticAnalysis
  script:
    gradle :services:course-service:pmdMain :services:course-service:pmdTest

course-service_test:
  stage: test
  script:
    gradle :services:course-service:test

