image: registry.fvdh.dev/gradle:6.7-jdk11

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

shared_build:
  stage: build
  script:
    gradle --build-cache :services:shared:assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build/
      - .gradle/

shared_checkStyle:
  stage: staticAnalysis
  script:
    gradle :services:shared:checkstyleMain :services:shared:checkstyleTest

shared_PMD:
  stage: staticAnalysis
  script:
    gradle :services:shared:pmdMain :services:shared:pmdTest

shared_test:
  stage: test
  script:
    gradle :services:shared:test

